<form class="b-sign b-ajaxForm" method="post" role="b-ajaxForm" action="<?php echo $this->url(array(), 'userSignInSend')?>">
    <h2 class="b-sign__heading">Sign in</h2>
    <div class="b-ajaxForm__row">
        <input name="email" type="text" class="input-block-level" placeholder="Email address">
    </div>
    <div class="b-ajaxForm__row">
        <input name="password" type="password" class="input-block-level" placeholder="Password">
    </div>
    <button class="btn btn-large btn-primary" type="submit">Sign in</button>
</form>